---
# Ansible collection dependencies for ludus_litterbox role
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: ansible.windows
    version: ">=2.0.0"
  - name: community.windows
    version: ">=2.0.0"
  - name: chocolatey.chocolatey
    version: ">=1.5.0"
